[package]
name = "jamiw1/notebookui"
version = "0.1.2"
repository = "https://github.com/jamiw1/NotebookUI"
authors = ["jamied <hey@isuckat.dev>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["src/client", ".luaurc", "aftman.toml", "selene.toml"]

[dependencies]
